name: Cleanup Stale Branches

on:
  # schedule:
  #   - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  stale-branch-cleanup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup GitHub CLI
      - name: Setup GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Identify and process stale branches
      - name: Identify Stale Branches
        id: stale-branches
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          echo "Fetching branches..."
          stale_branches=$(gh api repos/${{ github.repository }}/branches --jq '.[] | select(.name != "main" and .name != "develop") | select(.commit.committer.date < now - (180*86400)) | .name')

          if [ -z "$stale_branches" ]; then
            echo "No stale branches found."
            exit 0
          fi

          echo "Stale branches found: $stale_branches"
          echo "::set-output name=branches::$stale_branches"

      # Step 4: Create PR and close stale branches
      - name: Raise PR and Close Stale Branches
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          branches=${{ steps.stale-branches.outputs.branches }}
          for branch in $branches; do
            echo "Processing branch: $branch"

            # Create a PR against the default branch
            pr_url=$(gh pr create --head "$branch" --base "main" --title "Housekeeping: Cleanup $branch" --body "Preserving changes from stale branch $branch.")

            echo "PR created: $pr_url"

            # Immediately close the PR
            gh pr close "$pr_url" --comment "Closing housekeeping PR for branch $branch. The branch will now be deleted."

            # Delete the stale branch
            gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/$branch
            echo "Branch $branch deleted."
          done
